In [0]:
! mkdir /root/.kaggle

In [0]:

! echo '{"username":"ashimasinghal","key":"836908d1dfe1b0b189fd340660403893"}' > /root/.kaggle/kaggle.json  

In [0]:
! chmod 600 /root/.kaggle/kaggle.json

In [4]:
! kaggle competitions download -c prudential-life-insurance-assessment



  0% 0.00/2.42M [00:00<?, ?B/s]
100% 2.42M/2.42M [00:00<00:00, 146MB/s]
  0% 0.00/819k [00:00<?, ?B/s]
100% 819k/819k [00:00<00:00, 195MB/s]
  0% 0.00/24.9k [00:00<?, ?B/s]
100% 24.9k/24.9k [00:00<00:00, 22.4MB/s]


In [5]:
!unzip train.csv
!unzip test.csv


Archive:  train.csv.zip
  inflating: train.csv               
Archive:  test.csv.zip
  inflating: test.csv                


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
dataset = pd.read_csv('train.csv')
dataset.head(10)

Id  Product_Info_1  ... Medical_Keyword_48  Response
0   2               1  ...                  0         8
1   5               1  ...                  0         4
2   6               1  ...                  0         8
3   7               1  ...                  0         8
4   8               1  ...                  0         8
5  10               1  ...                  0         8
6  11               1  ...                  0         8
7  14               1  ...                  0         1
8  15               1  ...                  0         8
9  16               1  ...                  0         1

[10 rows x 128 columns]

In [8]:
dataset.keys()

Index(['Id', 'Product_Info_1', 'Product_Info_2', 'Product_Info_3',
       'Product_Info_4', 'Product_Info_5', 'Product_Info_6', 'Product_Info_7',
       'Ins_Age', 'Ht',
       ...
       'Medical_Keyword_40', 'Medical_Keyword_41', 'Medical_Keyword_42',
       'Medical_Keyword_43', 'Medical_Keyword_44', 'Medical_Keyword_45',
       'Medical_Keyword_46', 'Medical_Keyword_47', 'Medical_Keyword_48',
       'Response'],
      dtype='object', length=128)

In [9]:
from numpy import NaN, NAN , nan
dataset['Medical_History_1'].value_counts(dropna = False).head()

NaN    8889
1.0    7657
2.0    5727
0.0    4789
3.0    4722
Name: Medical_History_1, dtype: int64

In [10]:
dataset.fillna(method='pad')

Id  Product_Info_1  ... Medical_Keyword_48  Response
0          2               1  ...                  0         8
1          5               1  ...                  0         4
2          6               1  ...                  0         8
3          7               1  ...                  0         8
4          8               1  ...                  0         8
...      ...             ...  ...                ...       ...
59376  79142               1  ...                  0         4
59377  79143               1  ...                  0         7
59378  79144               1  ...                  0         8
59379  79145               1  ...                  0         8
59380  79146               1  ...                  0         7

[59381 rows x 128 columns]

In [11]:
data = dataset.drop(['Product_Info_2'], axis = 1)
data = data.fillna(method= 'ffill')
data = data.fillna(method= 'bfill')
data['Medical_History_1'].value_counts(dropna = False).head()

1.0    9016
2.0    6771
0.0    5639
3.0    5569
4.0    4350
Name: Medical_History_1, dtype: int64

In [12]:
#data = data.drop(['Medical_Keyword_10','Medical_Keyword_11','Medical_Keyword_12','Medical_Keyword_13'], axis = 1)
#data = data.drop(['Medical_Keyword_14'
 #                ,'Medical_Keyword_15','Medical_Keyword_15','Medical_Keyword_16','Medical_Keyword_17',
  #               'Medical_Keyword_18','Medical_Keyword_19','Medical_Keyword_20'], axis = 1)
data = data.drop(['Medical_Keyword_21',
                'Medical_Keyword_22','Medical_Keyword_23','Medical_Keyword_24','Medical_Keyword_25','Medical_Keyword_26',
                 'Medical_Keyword_27','Medical_Keyword_28'],axis = 1)
#data = data.drop(['Medical_Keyword_29','Medical_Keyword_30'], axis =1)
data.shape

(59381, 119)

In [13]:
data.head(10)

Id  Product_Info_1  ...  Medical_Keyword_48  Response
0   2               1  ...                   0         8
1   5               1  ...                   0         4
2   6               1  ...                   0         8
3   7               1  ...                   0         8
4   8               1  ...                   0         8
5  10               1  ...                   0         8
6  11               1  ...                   0         8
7  14               1  ...                   0         1
8  15               1  ...                   0         8
9  16               1  ...                   0         1

[10 rows x 119 columns]

In [0]:
df = data.sample(frac=0.7)

In [15]:
df_array= df.values
df_array

array([[3.4377e+04, 1.0000e+00, 2.6000e+01, ..., 0.0000e+00, 0.0000e+00,
        8.0000e+00],
       [4.9212e+04, 1.0000e+00, 2.6000e+01, ..., 0.0000e+00, 0.0000e+00,
        7.0000e+00],
       [7.1780e+04, 1.0000e+00, 2.6000e+01, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+00],
       ...,
       [6.0183e+04, 1.0000e+00, 2.6000e+01, ..., 0.0000e+00, 0.0000e+00,
        6.0000e+00],
       [3.6183e+04, 1.0000e+00, 2.6000e+01, ..., 0.0000e+00, 0.0000e+00,
        7.0000e+00],
       [6.7198e+04, 1.0000e+00, 2.6000e+01, ..., 0.0000e+00, 0.0000e+00,
        8.0000e+00]])

In [16]:
X = df_array[:, 0:126]
Y = df_array[:,-1]
X.shape, Y.shape

((41567, 119), (41567,))

In [0]:
from sklearn import preprocessing

In [0]:

min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [19]:
X_scale

array([[0.43431344, 0.        , 0.66666667, ..., 0.        , 0.        ,
        1.        ],
       [0.62176369, 0.        , 0.66666667, ..., 0.        , 0.        ,
        0.85714286],
       [0.90692561, 0.        , 0.66666667, ..., 0.        , 0.        ,
        0.42857143],
       ...,
       [0.76038968, 0.        , 0.66666667, ..., 0.        , 0.        ,
        0.71428571],
       [0.45713347, 0.        , 0.66666667, ..., 0.        , 0.        ,
        0.85714286],
       [0.84902895, 0.        , 0.66666667, ..., 0.        , 0.        ,
        1.        ]])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(X_scale, Y, test_size=0.3)

In [21]:
print(X_train.shape, X_val.shape)
print(Y_train.shape, Y_val.shape)

(29096, 119) (12471, 119)
(29096,) (12471,)


In [22]:
Y_train

array([1., 8., 6., ..., 6., 8., 8.])

In [0]:
from sklearn.linear_model import LinearRegression

In [24]:
model = LinearRegression()
model.fit(X_train, Y_train)
model.score(X_val, Y_val)


1.0

In [25]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense , Dropout

Using TensorFlow backend.


In [27]:

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(100,input_shape=(119,)))
model.add(tf.keras.layers.Activation('relu'))

model.add(tf.keras.layers.Dense(100))
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.Dense(100))
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.Dense(1))
model.add(tf.keras.layers.Activation('linear'))          #activation is linear called identity y = x, as linear regression

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 100)               12000     
_________________________________________________________________
activation_4 (Activation)    (None, 100)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 100)               10100     
_________________________________________________________________
activation_5 (Activation)    (None, 100)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 100)               10100     
_________________________________________________________________
activation_6 (Activation)    (None, 100)              

In [0]:
model.compile(optimizer='sgd',
                loss = 'mean_squared_error',
              metrics=['mse','mae'])

In [29]:
hist = model.fit(X_train, Y_train,
          batch_size=32, epochs=50,
          verbose=1,
          validation_data=(X_val, Y_val))

Train on 29096 samples, validate on 12471 samples
Epoch 1/50
29096/29096 [==============================] - 5s 158us/sample - loss: 2.0632 - mean_squared_error: 2.0632 - mean_absolute_error: 1.0451 - val_loss: 0.2594 - val_mean_squared_error: 0.2594 - val_mean_absolute_error: 0.4516
Epoch 2/50
29096/29096 [==============================] - 3s 98us/sample - loss: 0.4480 - mean_squared_error: 0.4480 - mean_absolute_error: 0.5239 - val_loss: 0.0700 - val_mean_squared_error: 0.0700 - val_mean_absolute_error: 0.2239
Epoch 3/50
29096/29096 [==============================] - 3s 95us/sample - loss: 0.3301 - mean_squared_error: 0.3301 - mean_absolute_error: 0.4488 - val_loss: 0.0988 - val_mean_squared_error: 0.0988 - val_mean_absolute_error: 0.2393
Epoch 4/50
29096/29096 [==============================] - 3s 97us/sample - loss: 0.2750 - mean_squared_error: 0.2750 - mean_absolute_error: 0.4080 - val_loss: 0.0393 - val_mean_squared_error: 0.0393 - val_mean_absolute_error: 0.1406
Epoch 5/50
29096/

In [0]:
X_data = pd.read_csv('test.csv')
X_data.head(10)

Id  Product_Info_1  ... Medical_Keyword_47  Medical_Keyword_48
0   1               1  ...                  0                   0
1   3               1  ...                  0                   0
2   4               1  ...                  0                   0
3   9               1  ...                  1                   1
4  12               1  ...                  0                   0
5  13               1  ...                  0                   0
6  21               1  ...                  0                   0
7  28               1  ...                  0                   0
8  30               1  ...                  0                   0
9  36               1  ...                  0                   0

[10 rows x 127 columns]

In [0]:
#X_data = X_data.drop(['Product_Info_2'])
X_data  = X_data.fillna(method='ffill')
X_data  = X_data.fillna(method='bfill')
X_data.head(10)

Id  Product_Info_1  ... Medical_Keyword_47  Medical_Keyword_48
0   1               1  ...                  0                   0
1   3               1  ...                  0                   0
2   4               1  ...                  0                   0
3   9               1  ...                  1                   1
4  12               1  ...                  0                   0
5  13               1  ...                  0                   0
6  21               1  ...                  0                   0
7  28               1  ...                  0                   0
8  30               1  ...                  0                   0
9  36               1  ...                  0                   0

[10 rows x 127 columns]

In [0]:
X_data = X_data.drop(['Medical_Keyword_21',
                'Medical_Keyword_22','Medical_Keyword_23','Medical_Keyword_24','Medical_Keyword_25',
                 'Medical_Keyword_27','Medical_Keyword_28'],axis = 1)
#data = data.drop(['Medical_Keyword_29','Medical_Keyword_30'], axis =1)
X_data.shape

KeyError: ignored

In [0]:
X_data = X_data.drop(['Product_Info_2'], axis = 1)
X_data.shape

(19765, 118)

In [0]:
X_test = X_data.values

In [0]:
model.predict(X_test)

ValueError: ignored